# Dockerfile    - contains all the info for running your software in a base container
# Dockerfile to Image 
# Dockerfile  ->>  Docker Clinet  ->>  Docker Server  ->>  Usable Image
#     |                  |                   |                      
# plain text        doker comp             Daemon       

# 1. choose a base image
# 2. run commands for software
# 3. specify the base command to be run at startup

# specify the base image
FROM alpine

# download and install dependencies
RUN apk add --update redis

# setup the startup command
CMD ["redis-server"]
