#!/bin/sh

mv background.png ../sayanta.png              # move & rename 

 
( Tr Cmd )
# tr Works on Characters
cat data.txt | tr a-z A-Z                               # pipe out on capital letter
echo sayanta | tr [:lower:] [:upper:] 
echo sayanta | tr "an" "AN"                             # work on character
echo sayanta | tr -d "a"                                # delete character
echo sayanta | tr -cd y                                 # complement delete
echo saayanta | tr -s "a"                               # squeeze remove repeated character
head 2 /dev/urandom | tr -cd [:print:]                  # delete everything except printable characters
echo sayanta1629 | tr -cd [:digit:]                     # del everything except num


( Sudo Cmd )
/etc/sudoers                                            # sudoers file
group sudo                                              # check user is sudoer  or not 
sudo usermod -aG sudo or wheel bot                      # set user to member of sudo 
sudo -l  --1st ALL is for host to use sudo,  2nd is for user,  3rd is for group,  4th is for commands that run user
sudo !!                                                 # use this if foget sudo
( sudo visudo )  --in 'user privilege specification' customize user permission access
newbot    ALL=(ALL:ALL) /usr/bin/apt,/usr/bin/ls        # restrict command for user
new bot    ALL=(ALL:ALL) NOPASSWD                       # don't ask pswd for commands
#if anything went wrong in "sudo visudo" file, use x for undo, e for re-edit the file and never user q bcus it's saves invalid changes


( Find Cmd )
find .                                                  # current dir
find ..                                                 # previous dir
find / -type f (folder)  d (directory)
find / -type f -iname *.txt                             # * means all .txt  (iname means case sensitive)
find / -iname dot*                                      # everything after dot
find / -size +1k  (c byte) (k kb) (M mb) (G gb)
find / -empty 
find / -perm 777
find / -group bandit7 -user bot 
find / ! -executable                                    # find not executable (!) means not
! exclude
find / -perm /g=s  (gid bit file)
find / -perm /u=s  (uid bit file)
find / -perm /a=x  (find all executable)
find / -perm /u=r  (all real only files)
find / -type f -perm 0777 -print -exec chmod 644 {} \;  # find particular perm file and change it to given permission
find / -type f -name "*.jpg" -exec rm -rf {} \;         # find and remove
find / -type -f -maxdepth 1                             # not recursively, show only curent dir files
find ~/ -type f -name ".*" -maxdepth 1                  # find hidden files
find / -type f  -mmin -20 (ago, +20 after)  -mtime -20 (days, +20 after)  -atime -20 (access time days) 
find . -type d -empty -delete                           # recusively remove all empty directories


( Locate Cmd )
locate -i ~/ bspwmrc            # locate file with ignorecase


( Permissions )
chmod u=rwx,g=rx,o=r file.sh    # give permissons linewise
4 --read
2 --write
1 --execute
chown root file.sh              # change file owner, only that owner will access
suid (octal value) 4            # special user id
sgid (octal value) 2            # special group id
sticky bit (octal value) 1


( GREP Cmd )
grep -w                         # exact word
grep -i                         # remove case sensitive
grep -n                         # show line number 
grep -B 4                       # show 4 lines before of maching
grep -C 4                       # 4 line before and after 
grep -A 4                       # show 4 lines after of matching
grep -win *.txt 
grep -win "sayanta" ./*/*       # seach in directory
grep -ri                        # recusively search with case sensitive
grep -l                         # list in which file contain match
grep -ric                       # count how many matches are in each file
grep "sayanta singh"            # use double quote or single while searching more than one word
grep ^sayanta                   # beginning of the line
grep ^[#] /etc/sudoers          --commented line
grep ^[^#] /etc/sudoers         # uncommneted line second caret is equivalent of not
grep sayanta$                   # end of the line
grep bot /etc/passwd /etc/group    # search in multiple files

( EGREP )                       # enhanced grep options are same like grep
egrep 'root|bot|daemon' /etc/passwd
grep -E 'root|bot|daemon' /etc/passwd    # grep -E equivalent of EGREP


( Control Operators )
;                  # seperate several cmds, use more than one cmd at a time
&                  # puts command in background and run other commands
echo $?            # show command fail or sucess, if output is 0 means previous cmd was sucess 
# &&                 # second command will execute only if first succeed
| |                # opposite of && only execute if 1st command fails
&&  | |    rm file && echo done | | echo not done      --if then else structure 
#                  --system don't read pound symbol
# \                  # line splitter


( Shortcuts )
!599  (!num)      # search with num in history command
!find  (!cmd)     # run previous find command


( Sed )
sed -n '20,30p'    # print line 20 to 30
 

( Hostname )
hostname -i       # ip address


( OS release )
cat /etc/os-release


( Regular Expression )


