#!/bin/sh

while true; do echo -ne "$(date)"; sleep 1; done
echo "!!" > <filename>     # create a script of last executed command
fuser -k <filename>        # kills a process that is locking a file        
<showkey -aALT> . || !*    # show parameter of previous command 
fc                         # edit long command in editor   
vim -x <filename>          # set password protection to a file  
du -b --max-depth 1 | sort -nr | perl -pe 's{([0-9]+)}{sprintf "%.1f%s", $1>=2**30? ($1/2**30, "G"): $1>=2**20? ($1/2**20, "M"): $1>=2**10? ($1/2**10, "K"): ($1, "")}e'    # sort the size usage of directory tree 
shutdown -h 12:00 "Server is going down for maintenance"    # shutdown the system at specific time
mount -t tmpfs tmpfs /mnt -o size=1024m    # mount a temporary ram partition


#Sys info
cat /etc/issue        # display distro 
cat /proc/version     # info about linux sys


#debian
sudo dpkg-repack firefox    # put an unpacked .deb package


#Network
python3 -m http.server 8000 || python -m http.server 
lsof -i || ss -p      # watch network service activity in real-time    
netstat -an | grep ESTABLISHED | awk '{print $5}' | awk -F: '{print $1}' | sort | uniq -c | awk '{ printf("%s	%s	",$2,$1) ; for (i = 0; i < $1; i++) {printf("*")}; print "" }'    - Greph # of connections of each hosts


#Web
wget -r -l1 --no-parent -nH -nd -P. -A".gif,.jpg" http://example.com/images    # download all images form site 
wget -m https://sayanta01.github.io/    # mirror an entire website                                                 
wget https://kali.download/virtual-images/kali-2022.3/kali-linux-2022.3-virtualbox-amd64.7z    # download iso
dig +short txt <keyword>.wp.dg.cx       # query wikipedia via console over DNS


#Fun
telnet towel.blinkenlights.nl
echo "You can simulate on-screen typing just like in the movies" | pv -qL 9
tr -c "[:digit:]" " " < /dev/urandom | dd cbs=$COLUMNS conv=unblock | GREP_COLOR="1;32" grep --color "[^ ]"    # matrix style
cat /dev/urandom | hexdump -C | grep "ca fe"    # pretend to be busy 
while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &    # set a console clock into the right corner


#Vid and Audio
import -window root screenshot.png




